package autocode

type ServiceGroup struct {
	// Code generated by github.com/tmnhs/admin-mall/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/tmnhs/admin-mall/server End; DO NOT EDIT.
}
