package autocode

type ApiGroup struct {
	// Code generated by github.com/tmnhs/admin-mall/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/tmnhs/admin-mall/server End; DO NOT EDIT.
}
