package autocode

type RouterGroup struct {
	// Code generated by github.com/tmnhs/admin-mall/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/tmnhs/admin-mall/server End; DO NOT EDIT.
}
